# Generated by Django 5.2.8 on 2025-11-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_profile_pf_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pf_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
