# Generated by Django 5.2.8 on 2025-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_profile_pf_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pf_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
